# Generated by Django 3.1.5 on 2021-02-20 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='دسته')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='متن')),
                ('approving', models.BooleanField(default=False, verbose_name='تایید پست')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان انتشار')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
            },
        ),
        migrations.CreateModel(
            name='FatherCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='بالادسته')),
            ],
            options={
                'verbose_name': 'بالا دسته بندی',
                'verbose_name_plural': 'بالا دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Like_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection', models.BooleanField(blank=True, null=True, verbose_name='پسند')),
            ],
            options={
                'verbose_name': 'پسند پست',
                'verbose_name_plural': 'پسند پست ها',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='چسب')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب ها',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('text', models.TextField(max_length=1000, verbose_name='متن')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/posts/', verbose_name='تصویر')),
                ('approving', models.BooleanField(default=False, verbose_name='تایید پست')),
                ('activate', models.BooleanField(default=True, verbose_name='قابلیت نمایش')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان انتشار')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.category', verbose_name='دسته بندی')),
                ('tag', models.ManyToManyField(to='posts.Tag', verbose_name='برچسب')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_user', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('user_comments', models.ManyToManyField(default=None, related_name='post_comment', through='posts.Comment', to=settings.AUTH_USER_MODEL, verbose_name='نظر')),
                ('user_likes', models.ManyToManyField(default=None, related_name='post_selection', through='posts.Like_Post', to=settings.AUTH_USER_MODEL, verbose_name='پسند')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست ها',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.AddField(
            model_name='like_post',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
        migrations.AddField(
            model_name='like_post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Like_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection', models.BooleanField(blank=True, null=True, verbose_name='پسند')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پسند نظر',
                'verbose_name_plural': 'پسند نظر ها',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='like_dislike',
            field=models.ManyToManyField(default=None, related_name='selection', through='posts.Like_Comment', to=settings.AUTH_USER_MODEL, verbose_name='پسند'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_post', to='posts.post', verbose_name='پست'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='category',
            name='fatherCat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.fathercat', verbose_name='بالا دسته بندی'),
        ),
    ]
