# Generated by Django 3.1.5 on 2021-02-22 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210221_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='like_dislike',
        ),
    ]
