# Generated by Django 3.1.5 on 2021-02-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_comment_like_dislike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/posts/%Y/%m/', verbose_name='تصویر'),
        ),
    ]
