# Generated by Django 3.1.5 on 2021-03-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20210225_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='posts.Tag', verbose_name='برچسب'),
        ),
    ]
