# Generated by Django 3.1.5 on 2021-03-04 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20210303_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': [('accept_comment', 'تایید نظر')], 'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_date',), 'permissions': [('accept_post', 'تایید پست')], 'verbose_name': 'پست', 'verbose_name_plural': 'پست ها'},
        ),
    ]
