# Generated by Django 3.1.5 on 2021-03-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20210304_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='approving',
            field=models.BooleanField(default=False, verbose_name='تایید نظر'),
        ),
    ]
