# Generated by Django 3.1.5 on 2021-03-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20210309_2106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': [('approve_comment', 'تایید نظر')], 'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_date',), 'permissions': [('approve_post', 'تایید پست')], 'verbose_name': 'پست', 'verbose_name_plural': 'پست ها'},
        ),
        migrations.AddField(
            model_name='comment',
            name='activate',
            field=models.BooleanField(default=True, verbose_name='فعال کردن نظر'),
        ),
    ]
