# Generated by Django 3.1.5 on 2021-03-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20210309_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_date',), 'permissions': [('approve_post', 'تایید پست'), ('active_post', 'قابلیت نمایش پست')], 'verbose_name': 'پست', 'verbose_name_plural': 'پست ها'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='activate',
            field=models.BooleanField(default=True, verbose_name='قابلیت نمایش'),
        ),
    ]
