# Generated by Django 3.1.5 on 2021-03-10 12:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0016_auto_20210309_2138'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dislike_Comment',
            new_name='DislikeComment',
        ),
        migrations.RenameModel(
            old_name='Dislike_Post',
            new_name='DislikePost',
        ),
        migrations.RenameModel(
            old_name='Like_Comment',
            new_name='LikeComment',
        ),
        migrations.RenameModel(
            old_name='Like_Post',
            new_name='LikePost',
        ),
    ]
