# Generated by Django 3.1.5 on 2021-03-10 12:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0017_auto_20210310_1546'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DislikeComment',
            new_name='Dislike_Comment',
        ),
        migrations.RenameModel(
            old_name='DislikePost',
            new_name='Dislike_Post',
        ),
        migrations.RenameModel(
            old_name='LikeComment',
            new_name='Like_Comment',
        ),
        migrations.RenameModel(
            old_name='LikePost',
            new_name='Like_Post',
        ),
    ]
