# Generated by Django 3.1.5 on 2021-01-31 17:30

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='دسته')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='متن')),
                ('approving', models.BooleanField(default=False, verbose_name='تایید پست')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
            },
        ),
        migrations.CreateModel(
            name='FatherCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='بالادسته')),
            ],
            options={
                'verbose_name': 'بالا دسته بندی',
                'verbose_name_plural': 'بالا دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Like_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection', models.BooleanField(blank=True, null=True, verbose_name='پسند')),
            ],
            options={
                'verbose_name': 'پسند پست',
                'verbose_name_plural': 'پسند پست ها',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='چسب')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب ها',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='نام کاربری')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='پست الکتریکی')),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact Phone Number!', max_length=31, unique=True, verbose_name='تلفن همراه')),
                ('image', models.ImageField(upload_to='img/users/')),
                ('start_time', models.DateField(blank=True, verbose_name='زمان ثبت نام')),
                ('login_time', models.DateField(blank=True, verbose_name='زمان آخرین بازدید')),
                ('password', models.CharField(max_length=30, verbose_name='کلمه عبور')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('text', models.CharField(max_length=1000, verbose_name='متن')),
                ('image', models.ImageField(upload_to='img/posts/')),
                ('sendign_time', models.DateTimeField(verbose_name='زمان ارسال پست')),
                ('approving', models.BooleanField(default=False, verbose_name='تایید پست')),
                ('activate', models.BooleanField(default=True, verbose_name='قابلیت نمایش')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.category', verbose_name='دسته بندی')),
                ('comment', models.ManyToManyField(default=None, related_name='post_comment', through='post.Comment', to='post.User', verbose_name='نظر')),
                ('like_dislike', models.ManyToManyField(default=None, related_name='post_selection', through='post.Like_Post', to='post.User', verbose_name='پسند')),
                ('tag', models.ManyToManyField(to='post.Tag', verbose_name='برچسب')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_user', to='post.user', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست ها',
            },
        ),
        migrations.AddField(
            model_name='like_post',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post'),
        ),
        migrations.AddField(
            model_name='like_post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.user'),
        ),
        migrations.CreateModel(
            name='Like_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection', models.BooleanField(blank=True, null=True, verbose_name='پسند')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.user')),
            ],
            options={
                'verbose_name': 'پسند نظر',
                'verbose_name_plural': 'پسند نظر ها',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='like_dislike',
            field=models.ManyToManyField(default=None, related_name='selection', through='post.Like_Comment', to='post.User', verbose_name='پسند'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_post', to='post.post', verbose_name='پست'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to='post.user', verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='category',
            name='fatherCat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.fathercat'),
        ),
    ]
