# Generated by Django 3.1.5 on 2021-02-03 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20210203_1216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر وبلاگ', 'verbose_name_plural': 'کاربرهای وبلاگ'},
        ),
        migrations.AlterField(
            model_name='category',
            name='fatherCat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.fathercat', verbose_name='بالا دسته بندی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/users/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, unique=True, verbose_name='تلفن همراه'),
        ),
    ]
