# Generated by Django 3.1.5 on 2021-02-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_remove_post_sendign_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comment',
            new_name='user_comments',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='like_dislike',
            new_name='user_likes',
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان انتشار'),
        ),
        migrations.AlterField(
            model_name='user',
            name='start_time',
            field=models.DateField(auto_now_add=True, verbose_name='زمان ثبت نام'),
        ),
    ]
