# Generated by Django 3.1.5 on 2021-02-16 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0008_auto_20210214_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='like_dislike',
            field=models.ManyToManyField(default=None, related_name='selection', through='post.Like_Comment', to=settings.AUTH_USER_MODEL, verbose_name='پسند'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='like_comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like_post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_user', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_comments',
            field=models.ManyToManyField(default=None, related_name='post_comment', through='post.Comment', to=settings.AUTH_USER_MODEL, verbose_name='نظر'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_likes',
            field=models.ManyToManyField(default=None, related_name='post_selection', through='post.Like_Post', to=settings.AUTH_USER_MODEL, verbose_name='پسند'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
