# Generated by Django 3.1.5 on 2021-02-17 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20210216_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='fatherCat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.fathercat', verbose_name='بالا دسته بندی'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/posts/', verbose_name='تصویر'),
        ),
    ]
