# Generated by Django 3.1.5 on 2021-02-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='نام کاربری')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='پست الکتریکی')),
                ('phone', models.CharField(max_length=15, null=True, verbose_name='تلفن همراه')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/users/', verbose_name='تصویر')),
                ('start_time', models.DateField(auto_now_add=True, verbose_name='زمان ثبت نام')),
                ('login_time', models.DateField(auto_now=True, verbose_name='زمان آخرین بازدید')),
                ('password', models.CharField(max_length=30, verbose_name='کلمه عبور')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'کاربر وبلاگ',
                'verbose_name_plural': 'کاربرهای وبلاگ',
            },
        ),
    ]
