# Generated by Django 3.1.5 on 2021-02-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.PositiveBigIntegerField(verbose_name='تلفن همراه'),
        ),
    ]
