# Generated by Django 3.1.5 on 2021-02-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210220_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='تلفن همراه'),
        ),
    ]
