# Generated by Django 3.1.5 on 2021-02-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210221_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/users/%Y/%m/', verbose_name='تصویر'),
        ),
    ]
